recipe: default.v1
language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  # - name: RegexEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    constrain_similarities: true
    max_history: 5
    epochs: 200
  - name: RulePolicy